/* SmartIT Pro SQL Server business schema. ASP.NET Identity tables are maintained by EF Core migrations. */
IF DB_ID(N'SmartITPro') IS NULL CREATE DATABASE SmartITPro;
GO
USE SmartITPro;
GO
CREATE TABLE Departments (Id uniqueidentifier NOT NULL PRIMARY KEY, Name nvarchar(256) NOT NULL UNIQUE, CreatedAt datetime2 NOT NULL, UpdatedAt datetime2 NULL);
CREATE TABLE Employees (Id uniqueidentifier NOT NULL PRIMARY KEY, FirstName nvarchar(100) NOT NULL, LastName nvarchar(100) NOT NULL, Email nvarchar(256) NOT NULL, JobTitle nvarchar(256) NULL, ProfilePhotoPath nvarchar(max) NULL, DepartmentId uniqueidentifier NOT NULL, CreatedAt datetime2 NOT NULL, UpdatedAt datetime2 NULL, CONSTRAINT FK_Employees_Departments FOREIGN KEY(DepartmentId) REFERENCES Departments(Id));
CREATE TABLE Assets (Id uniqueidentifier NOT NULL PRIMARY KEY, AssetTag nvarchar(50) NOT NULL UNIQUE, Name nvarchar(150) NOT NULL, Type int NOT NULL, Manufacturer nvarchar(256) NULL, Model nvarchar(256) NULL, SerialNumber nvarchar(256) NULL, Status int NOT NULL, PurchaseDate datetime2 NULL, CreatedAt datetime2 NOT NULL, UpdatedAt datetime2 NULL);
CREATE TABLE AssetAssignments (Id uniqueidentifier NOT NULL PRIMARY KEY, AssetId uniqueidentifier NOT NULL, EmployeeId uniqueidentifier NOT NULL, AssignedAt datetime2 NOT NULL, ReturnedAt datetime2 NULL, Notes nvarchar(max) NULL, CreatedAt datetime2 NOT NULL, UpdatedAt datetime2 NULL, CONSTRAINT FK_Assignments_Assets FOREIGN KEY(AssetId) REFERENCES Assets(Id), CONSTRAINT FK_Assignments_Employees FOREIGN KEY(EmployeeId) REFERENCES Employees(Id));
CREATE TABLE Tickets (Id uniqueidentifier NOT NULL PRIMARY KEY, Number nvarchar(50) NOT NULL UNIQUE, Subject nvarchar(200) NOT NULL, Description nvarchar(max) NOT NULL, Priority int NOT NULL, Status int NOT NULL, RequesterId uniqueidentifier NULL, CreatedAt datetime2 NOT NULL, UpdatedAt datetime2 NULL, CONSTRAINT FK_Tickets_Employees FOREIGN KEY(RequesterId) REFERENCES Employees(Id));
CREATE TABLE TicketComments (Id uniqueidentifier NOT NULL PRIMARY KEY, TicketId uniqueidentifier NOT NULL, Author nvarchar(256) NOT NULL, Body nvarchar(max) NOT NULL, CreatedAt datetime2 NOT NULL, UpdatedAt datetime2 NULL, CONSTRAINT FK_Comments_Tickets FOREIGN KEY(TicketId) REFERENCES Tickets(Id));
CREATE TABLE TicketAttachments (Id uniqueidentifier NOT NULL PRIMARY KEY, TicketId uniqueidentifier NOT NULL, FileName nvarchar(260) NOT NULL, StoredPath nvarchar(max) NOT NULL, CreatedAt datetime2 NOT NULL, UpdatedAt datetime2 NULL, CONSTRAINT FK_Attachments_Tickets FOREIGN KEY(TicketId) REFERENCES Tickets(Id));
CREATE TABLE SoftwareLicenses (Id uniqueidentifier NOT NULL PRIMARY KEY, ProductName nvarchar(256) NOT NULL, LicenseKey nvarchar(512) NOT NULL, Seats int NOT NULL, UsedSeats int NOT NULL, ExpiresAt datetime2 NULL, CreatedAt datetime2 NOT NULL, UpdatedAt datetime2 NULL);
CREATE TABLE MaintenanceSchedules (Id uniqueidentifier NOT NULL PRIMARY KEY, AssetId uniqueidentifier NOT NULL, Description nvarchar(max) NOT NULL, ScheduledFor datetime2 NOT NULL, Completed bit NOT NULL, CreatedAt datetime2 NOT NULL, UpdatedAt datetime2 NULL, CONSTRAINT FK_Maintenance_Assets FOREIGN KEY(AssetId) REFERENCES Assets(Id));
CREATE TABLE AuditLogs (Id uniqueidentifier NOT NULL PRIMARY KEY, UserName nvarchar(256) NOT NULL, Action nvarchar(256) NOT NULL, EntityName nvarchar(256) NOT NULL, Details nvarchar(max) NULL, IpAddress nvarchar(64) NULL, CreatedAt datetime2 NOT NULL, UpdatedAt datetime2 NULL);
GO
