namespace SmartIT.Domain;

public abstract class Entity { public Guid Id { get; set; } = Guid.NewGuid(); public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime? UpdatedAt { get; set; } }
public enum AssetType { Laptop, DesktopPC, Printer, Switch, Router, Firewall, Phone, Monitor }
public enum AssetStatus { Available, Assigned, InMaintenance, Retired }
public enum TicketPriority { Low, Medium, High, Critical }
public enum TicketStatus { Open, InProgress, Resolved, Closed }

public class Department : Entity { public string Name { get; set; } = string.Empty; public ICollection<Employee> Employees { get; set; } = new List<Employee>(); }
public class Employee : Entity { public string FirstName { get; set; } = string.Empty; public string LastName { get; set; } = string.Empty; public string Email { get; set; } = string.Empty; public string? JobTitle { get; set; } public string? ProfilePhotoPath { get; set; } public Guid DepartmentId { get; set; } public Department? Department { get; set; } public ICollection<AssetAssignment> Assignments { get; set; } = new List<AssetAssignment>(); public string FullName => $"{FirstName} {LastName}"; }
public class Asset : Entity { public string AssetTag { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public AssetType Type { get; set; } public string? Manufacturer { get; set; } public string? Model { get; set; } public string? SerialNumber { get; set; } public AssetStatus Status { get; set; } = AssetStatus.Available; public DateTime? PurchaseDate { get; set; } public ICollection<AssetAssignment> Assignments { get; set; } = new List<AssetAssignment>(); }
public class AssetAssignment : Entity { public Guid AssetId { get; set; } public Asset? Asset { get; set; } public Guid EmployeeId { get; set; } public Employee? Employee { get; set; } public DateTime AssignedAt { get; set; } = DateTime.UtcNow; public DateTime? ReturnedAt { get; set; } public string? Notes { get; set; } }
public class Ticket : Entity { public string Number { get; set; } = string.Empty; public string Subject { get; set; } = string.Empty; public string Description { get; set; } = string.Empty; public TicketPriority Priority { get; set; } = TicketPriority.Medium; public TicketStatus Status { get; set; } = TicketStatus.Open; public Guid? RequesterId { get; set; } public Employee? Requester { get; set; } public ICollection<TicketComment> Comments { get; set; } = new List<TicketComment>(); public ICollection<TicketAttachment> Attachments { get; set; } = new List<TicketAttachment>(); }
public class TicketComment : Entity { public Guid TicketId { get; set; } public Ticket? Ticket { get; set; } public string Author { get; set; } = string.Empty; public string Body { get; set; } = string.Empty; }
public class TicketAttachment : Entity { public Guid TicketId { get; set; } public Ticket? Ticket { get; set; } public string FileName { get; set; } = string.Empty; public string StoredPath { get; set; } = string.Empty; }
public class SoftwareLicense : Entity { public string ProductName { get; set; } = string.Empty; public string LicenseKey { get; set; } = string.Empty; public int Seats { get; set; } public int UsedSeats { get; set; } public DateTime? ExpiresAt { get; set; } }
public class MaintenanceSchedule : Entity { public Guid AssetId { get; set; } public Asset? Asset { get; set; } public string Description { get; set; } = string.Empty; public DateTime ScheduledFor { get; set; } public bool Completed { get; set; } }
public class AuditLog : Entity { public string UserName { get; set; } = string.Empty; public string Action { get; set; } = string.Empty; public string EntityName { get; set; } = string.Empty; public string? Details { get; set; } public string? IpAddress { get; set; } }
